name: core_network
description: Network layer for Flutter applications with Dio integration
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  core_utils:
    path: ../core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 