name: core_router
description: Navigation and routing utilities for Flutter applications
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  core_utils:
    path: ../core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 